### ISSUE TITLE
What is the wiring diagram for this programmer board?

### ISSUE THREAD

**Issue by hientv1999** [adafruit/Adafruit_AVRProg#19]
Hi,

I know this is not the right place to ask questions. But I have researched all over the Internet but cannot find any information about how to connect the Arduino to an Attiny816 for programming with UPDI. Can someone please show me where to get a schematic for wiring. For example, jtag2updi library uses D6 for programming UPDI via 470 resistor. But I believe this library uses different the GPIO. Thank you.

Best regards

**Comment by dhalbert** [comment]
Would this help? https://learn.adafruit.com/adafruit-updi-friend. Please ask these kinds of questions in https://forums.adafruit.com or https://adafru.it/discord.

**Comment by hientv1999** [comment]
I initially thought it was just as simple as a resistor between TX and RX. But reading through the code, they use Serial for normal debug print, and Serial1 for UPDI. I don't know what the GPIO for Serial1? As I know, Uno only has 1 hardware serial interface. So how does this work?

**Comment by hientv1999** [comment]
I cannot compile this project in Arduino, obviously because Serial1 isn't available for Arduino Uno. But from the demonstration video of Adafruit, she used an Arduino Uno and still get debug log on serial monitor. I'm so confused. Please help

**Comment by dhalbert** [comment]
Please ask these kinds of questions in https://forums.adafruit.com/ or https://adafru.it/discord, and please give pointers there to the video you mean, the code, etc.
