### ISSUE TITLE
isp_transaction result including the first byte?

### ISSUE THREAD

**Issue by DeqingSun** [adafruit/Adafruit_AVRProg#2]
In the code:

https://github.com/adafruit/Adafruit_AVRProg/blob/32321918fce71668dddc7d86d495d4137c942d07/Adafruit_AVRProg.cpp#L168

It is comparing the return value of isp_transaction to 0x8000 to see if there is anything wrong. However, at least on my setup (t85), the AC also get returned. 

![Screen Shot 2021-04-02 at 8 25 03 PM](https://user-images.githubusercontent.com/1385273/113463009-adf75100-93f1-11eb-898c-fc73c5bfcac4.png)

If I change it to ```if (isp_transaction(0xAC, 0x80, 0, 0)&0xFFFF != 0x8000) { // chip erase``` it works.

Is it better to do low 2 bytes masks? or add AC here?

**Comment by ladyada** [comment]
please mask it! :)
